on: [push]
name: Azure ARM
env:
    ResourceGroupName: 'bvgo-dev-rg-armDeploy-abcde'
    Location: 'westeurope'
    
permissions:
  id-token: write
  contents: read
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:

        # Checkout code
      - uses: actions/checkout@main
      
      - name: Print 
        run: |
            echo ${{ env.ResourceGroupName }}
            echo ${{ env.Location }}
        
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
            
      - name: Create resource group
        uses: azure/CLI@v1
        with:
          inlineScript: |
            if $(az group exists --name ${{ env.ResourceGroupName }}) ; then
                echo "Resource group already exists"
            else
                az group create --name ${{ env.ResourceGroupName }} --location ${{ env.Location}} --tags "Afdeling=Data en Integratie" "Product=ASE" 
                echo "Resource group created"
            fi  
